%ifndef __BOOTINF_INC__INCLUDED__
%define __BOOTINF_INC__INCLUDED__

[extern BOOTINF]
[extern BOOTINF.BootDevice]
[extern BOOTINF.MMapAddr]
[extern BOOTINF.MMapEnts]
[extern BOOTINF.CurVBEInfo]
[extern BOOTINF.KernelStart]
[extern BOOTINF.KernelEnd]
[extern BOOTINF.ModList]
[extern BOOTINF.ModCount]
[extern BOOTINF.FrameBuffer]
[extern BOOTINF.Mem_Low]
[extern BOOTINF.Mem_High]
[extern VBEINFO]
[extern MODLIST]

%endif
