; -------------------------------------- --------------------------------------
;                                   BOS 0.0.5
;                                  BUILD: 0005
;                                 CPUID HEADER
;                          01/04/2016 - Brian T Hoover
; -----------------------------------------------------------------------------

extern INIT_CPUID
extern BSP.Vendor
extern BSP.Info
extern BSP.Features
extern BSP.ExtendedFeatures
extern BSP.ExtendedInfo
