; -------------------------------------- --------------------------------------
;                                   BOS 0.0.5
;                                  BUILD: 0005
;                               Linker Variables
;                          01/04/2016 - Brian T Hoover
; -----------------------------------------------------------------------------


extern BS_ReadFile
extern FILE_IO
extern AP_Strap
extern SVGA_puts
