; -------------------------------------- --------------------------------------
;                                   BOS 0.0.5
;                                  BUILD: 0004
;                             Read Only Data Header
;                          01/04/2016 - Brian T Hoover
; -----------------------------------------------------------------------------

extern MSG.Identify
extern MSG.ProcessorMode
extern MSG.BootDevice
extern MSG.GDT
extern MSG.A20
extern MSG.PM32
extern MSG.LM64
extern MSG.PDIR
extern MSG.PMM
extern MSG.VMM
extern MSG.Linker
extern MSG.PIC
extern MSG.MMAP
extern MSG.Done
extern MSG.Ok
extern MSG.No
extern MSG.Fail
extern MSG.Error
extern Files.PM_FAT
extern Files.PM_EXT
extern Files.PM_PXE
extern Files.LM_FAT
extern Files.LM_EXT
extern Files.LM_PXE
extern Files.PM_PMM
extern Files.PM_VMM
extern Files.PM_Link
extern Files.LM_PMM
extern Files.LM_VMM
extern Files.LM_Link
