; -------------------------------------- --------------------------------------
;                                   BOS 0.0.5
;                                  BUILD: 0004
;                             Read Only Data Header
;                          01/04/2016 - Brian T Hoover
; -----------------------------------------------------------------------------

extern MSG.Identify
extern MSG.ProcessorMode
extern MSG.BootDevice
extern MSG.GDT
extern MSG.A20
extern MSG.PM32
extern MSG.PDIR
extern MSG.LOADBUILD
extern MSG.PIC
extern MSG.MMAP
extern MSG.Done
extern MSG.Ok
extern MSG.No
extern MSG.Fail
extern MSG.Error
extern Files.FATDisk
extern Files.ExtDisk
extern Files.TFTPPXE
extern Files.BUILD86
extern Files.BUILD64
